[package]
name = "grokking-deep-learning-rs"
version = "0.1.0"
authors = ["Suyash <suyash93@protonmail.com>"]
edition = "2018"

[dependencies]
datasets = { path = "../datasets" }
rand = "0.6.4"

[dev-dependencies]
rulinalg = "0.4.2"
